name: Joint Entity Relation Extraction

# INFO: wandb
wandb: True
project: Filter
tag: default

# INFO: Run
num_worker: 12
batch_size: 16 # can be overrided by model.yaml
test_batch_size: 1
lr: 0.00005
task_lr: 0.0005
ner_lr: 0.0005
rel_lr: 0.00005
# decoder_lr: 0.00003
# Achieved by gradient accumulation
# accumulate_grad_batches will be set as global_batch_size // batch_size
global_batch_size: 64
warmup: 0.1

# INFO: Trainer
max_epochs: 30
# auto_lr: True
# fast_dev_run: True
precision: 16
# reload_dataloaders_every_epoch: True

# INFO: Model
max_seq_len: 400
model_config: models/configs/bert.yaml # can not be modified in ext_config

# INFO: Dataset
context_window: 500  # make sure that context_window < max_seq_len
dataset_config: datasets/ace2005/ace2005.yaml # can not be modified in ext_config

# INFO: sub-task
use_ner: "mlp"
use_rel: "mlp"
use_filter: True
use_two_plm: False
use_cache: True

use_warmup_filter: 20
use_warmup_rel: 10

use_bio_embed: True
# use_ent_pred_rel: "embed2" # for compatibility
use_rel_opt3: "embed2"
use_filter_opt1: "concat_pro"
use_filter_opt5: "u1"

# Graph
use_graph_layers: 0

# loss rate
ner_rate: 1
rel_rate: 1
filter_rate: 1
rel_ner_rate: 0.1

# Filter
use_rel_opt1: "obj"
use_rel_opt2: "mean"
use_filter_hard: False
use_thres_val: False
use_thres_plus: True
use_gold_ent_val: False
use_gold_filter_val: False
use_filter_label_enhance: False
use_filter_loss_sum: 100
use_rel_ner: True

# 待验证
use_spert: False # defeat
# use_spert_opt1: "max" # defeat
# use_rel_cat: "none" # default none, pure
# use_crf: False # 目前效果不太行
# use_dynamic_rel_threshold: True
use_thres_threshold: 0.0001
ent_attn_layer_num: 1
ent_mlp_layer_num: 2

# lota
use_ent_tag_cross_attn: True
use_filter_sum_loss: True
use_loss_fix: True

# set
use_ent_attn: True
ent_attn_range: 10
use_thres_train: True
