name: Joint Entity Relation Extraction

# wandb
wandb: True
project: theta
tag: default

# Run
batch_size: 8
max_epochs: 30
lr: 0.0001
decoder_lr: 0.001

# Trainer
# auto_lr: True

# Model
max_seq_len: 160
model_config: models/albert.yaml

# Dataset
context_window: 0  # make sure that context_window < max_seq_len
dataset_config: datasets/ace2005/ace2005.yaml