name: Joint Entity Relation Extraction

# INFO: wandb
wandb: True
project: theta
tag: default

# INFO: Run
batch_size: 16 # can be overrided by model.yaml
lr: 0.00003
# decoder_lr: 0.00003
# Achieved by gradient accumulation
# accumulate_grad_batches will be set as global_batch_size // batch_size
global_batch_size: 16
warmup: 0.1

# INFO: Trainer
max_epochs: 30
# auto_lr: True
# fast_dev_run: True

# INFO: Model
max_seq_len: 180
model_config: models/configs/bert.yaml # can not be modified in ext_config

# INFO: Dataset
context_window: 180  # make sure that context_window < max_seq_len
dataset_config: datasets/ace2005/ace2005.yaml # can not be modified in ext_config

# INFO: sub-task
use_span: "" # lmhead, multi_classifier
use_ner: "lmhead"
use_crf: False
use_rel_cls: "lmhead"
use_ent_type_in_rel: False
use_independent_plm: False
use_two_stage: False

use_ent_corres: "" # deprecated
use_rel_maps: "" # deprecated
